version: '3.5'

services:
  postgres:
    container_name: powerstack-postgres
    image: postgres:14.5
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: powerstack
    command: -p 5432

  apollo:
    container_name: powerstack-apollo
    image: powerstack-apollo:local
    ports:
      - '${APOLLO_SERVICE_PORT}:${APOLLO_SERVICE_PORT}'
    depends_on:
      - postgres
    restart: always
    environment:
      PORT: ${APOLLO_SERVICE_PORT}

  hasura:
    container_name: powerstack-hasura
    image: powerstack-hasura:local
    ports:
      - '${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}'
    depends_on:
      - postgres
      - apollo
    links:
      - apollo
    restart: always
    environment:
      # https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:pass@postgres:5432/powerstack?sslmode=disable
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT}
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      HASURA_CUSTOM_REMOTE_SCHEMA_URL: http://apollo:${APOLLO_SERVICE_PORT}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anon

  auth:
    container_name: powerstack-auth
    image: powerstack-auth:local
    ports:
      - '${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}'
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/powerstack?sslmode=disable
      PORT: ${AUTH_SERVICE_PORT}
      SERVER_SECRET: super
      HOSTNAME: '0.0.0.0'
      JWT_SECRET: '{"type":"HS256","key":"xx52fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f402ddfbb8b58eb5bd11ba225136a6af45bbae07ca872f4","issuer":"hasura-auth"}'
      JWT_TOKEN_EXPIRATION: 86400
      TWITTER_CONSUMER_KEY: xx
      TWITTER_CONSUMER_SECRET: xx
      TWITTER_CALLBACK: http://localhost:4001/provider/twitter/cb
      TWITTER_CLIENT_ID: xx
      TWITTER_CLIENT_SECRET: xx

volumes:
  pg-data:

networks:
  default:
    name: powerstack
